### ISSUE TITLE
Build fails when using `ipv6` and Musl.

### ISSUE THREAD

**Issue by StefanJum** [unikraft/lib-lwip#24]
When building with Musl and enabling `ipv6`, the build fails with this error:

```make
liblwip/origin/fork-lwip-UNIKRAFT-2_1_x/src/include/lwip/inet.h:155:82: error: ‘struct in6_addr’ has no member named ‘un’
  155 | #define inet6_addr_from_ip6addr(target_in6addr, source_ip6addr) {(target_in6addr)->un.u32_addr[0] = (source_ip6addr)->addr[0]; \

```

The definition of `struct in6_addr` [in lwip's `in.h`](https://github.com/lwip-tcpip/lwip/blob/master/src/include/lwip/inet.h#L71) is overriten by the definition in [musl's `in.h`](https://git.musl-libc.org/cgit/musl/tree/include/netinet/in.h?h=v1.1.19&id=55df09bfccbfe21fc9dd7d8f94550c0ff25ace04#n23), wich does not include any member named `un`.

This happens in case `musl` is places before `lwip` in the `Makefile`.
Changing the order of the libraries does not seem to work here.

**Comment by razvand** [comment]
Solved by #25
